### ISSUE TITLE
Did the video had to be mp4?

### ISSUE THREAD

**Issue by Rck27** [Boidushya/FrameBot#10]
I get this error

Extract Frames?(y/n)
>y
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/bot/main.py", line 87, in <module>
    extractFrames()
  File "/data/data/com.termux/files/home/bot/main.py", line 31, in extractFrames
    file = os.listdir('./assets/video')[0]
FileNotFoundError: [Errno 2] No such file or directory: './assets/video'

I already place an video,a short video for testing
It named video.mp4
I using terminal emulator

**Comment by boidushya** [comment]
You need to place the video in `assets/video` folder. Seems like that folder does not exist. And as far as I'm aware, no, the file format can be anything as long as its a video.

**Comment by Rck27** [comment]
> You need to place the video in `assets/video` folder. Seems like that folder does not exist. And as far as I'm aware, no, the file format can be anything as long as its a video.

Its already inside
Can i modify it to mount from storage instead? Im using terminal emulator

**Comment by boidushya** [comment]
yes you can, message me on discord: semolini#2344
