### ISSUE TITLE
seems cant extract the frames

### ISSUE THREAD

**Issue by afrizal1221** [Boidushya/FrameBot#14]
rameBot ➤ sudo python3 main.py                                             git:master*
Extract Frames?(y/n) 
>y
Traceback (most recent call last):
  File "main.py", line 21, in wrapper
    return job_func(*args, **kwargs)
  File "main.py", line 68, in post
    currentFrame = f'assets/frames/{dir[0]}'
IndexError: list index out of range

here's the output

**Comment by boidushya** [comment]
Have you checked #12 ? This might be causing the problem. If that's not the case, check if you have the right opencv installed. If that doesn't work as well, message me on discord semolini#2344
