### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Beteoto** [Boidushya/FrameBot#24]
Hi, when i tried to extract the frames and the program asked me to do, it said this:
AttributeError: 'str' object has no attribute 'mp4'

![image](https://user-images.githubusercontent.com/67559786/105780839-36ef9900-5f26-11eb-870e-a4b20da1d1ef.png)

Why this happens?

**Comment by boidushya** [comment]
Seems like you manually changed line 32 from `{file}` to  `{file.mp4}`
Change that back and it should be good.
