### ISSUE TITLE
http://maxbots.ddns.net/token/ site can't opened.

### ISSUE THREAD

**Issue by jesayafn** [Boidushya/FrameBot#3]
I have tried going through http://maxbots.ddns.net/token/, but the website won't open.

`ERR_CONNECTION_TIMED_OUT`

Then I have tried using an alternative, namely through the Graph API Explorer to get an access token to my page. But I got into new problems like this:
```
File "main.py", line 21, in wrapper
    return job_func(*args, **kwargs)
  File "main.py", line 74, in post
    post_id = graph.put_photo(image=open(currentFrame, 'rb'),message = msg)['post_id']
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\facebook\__init__.py", line 223, in put_photo
    return self.request(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\facebook\__init__.py", line 313, in request
    raise GraphAPIError(result)
facebook.GraphAPIError: (#200) Permissions error

```

**Could someone help me to solve this problem?**

**Comment by boidushya** [comment]
Hey! The recent changelog on facebooks graph api mentions that you can now create your own token without verifying an app...
I have tested it out and it works!
Try following [this tutorial ](https://medium.com/@Jenananthan/how-to-create-non-expiry-facebook-page-token-6505c642d0b1?fbclid=IwAR0Bzs1SZCYxAfPBPc-ov-lWHSGgHqb3hSt886sQrRBXALGKklRdEK9CMUc) to get an access token set to never expire and add "page_manage_posts" and "page_manage_engagements" permissions to your app in Graph API Explorer

**Comment by jesayafn** [comment]
Thanks a lot.

**Comment by jesayafn** [comment]
I have one new issue, namely the upload from the bot does not appear and it happens because the application in Fb Dev is in development mode, but when I activate the application it can display the bot's upload but instead it makes me unable to generate tokens according to the required permissions.

**Do you have a solution?**

**Comment by boidushya** [comment]
Message me on discord semolini#2344, ill explain it in detail there

**Comment by boidushya** [comment]
[Check this out](https://github.com/Boidushya/FrameBot/blob/master/generateToken.md
)

**Comment by jesayafn** [comment]
Thanks a lot.
